/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1TradesQueryParams, GetV1Trades200, GetV1TradesQueryResponse } from "../types/GetV1Trades.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

export const getV1TradesQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(200).default(50)
    }) as unknown as ToZod<GetV1TradesQueryParams>

/**
 * @description Default Response
 */
export const getV1Trades200Schema = z.object({
    "trades": z.array(z.object({
    "id": z.uuid(),
"asset_id": z.string(),
"side": z.enum(["buy", "sell"]),
"usd_amount": z.string(),
"qty": z.string(),
"price_at_execution": z.string(),
"idempotency_key": z.string(),
"created_at": z.string()
    }))
    }) as unknown as ToZod<GetV1Trades200>

export const getV1TradesQueryResponseSchema = getV1Trades200Schema as unknown as ToZod<GetV1TradesQueryResponse>