/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1LeaderboardQueryParams, GetV1Leaderboard200, GetV1LeaderboardQueryResponse } from "../types/GetV1Leaderboard.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

export const getV1LeaderboardQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(200).default(50)
    }) as unknown as ToZod<GetV1LeaderboardQueryParams>

/**
 * @description Default Response
 */
export const getV1Leaderboard200Schema = z.object({
    "week_starting_date": z.string(),
"entries": z.array(z.object({
    "rank": z.int().min(-9007199254740991).max(9007199254740991),
"user_id": z.uuid(),
"handle": z.union([z.string(), z.null()]),
"composite_score": z.int().min(-9007199254740991).max(9007199254740991)
    })),
"my_entry": z.union([z.object({
    "rank": z.int().min(-9007199254740991).max(9007199254740991),
"user_id": z.uuid(),
"handle": z.union([z.string(), z.null()]),
"composite_score": z.int().min(-9007199254740991).max(9007199254740991)
    }), z.null()])
    }) as unknown as ToZod<GetV1Leaderboard200>

export const getV1LeaderboardQueryResponseSchema = getV1Leaderboard200Schema as unknown as ToZod<GetV1LeaderboardQueryResponse>