/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1Health200, GetV1HealthQueryResponse } from "../types/GetV1Health.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const getV1Health200Schema = z.object({
    "status": z.enum(["ok"])
    }) as unknown as ToZod<GetV1Health200>

export const getV1HealthQueryResponseSchema = getV1Health200Schema as unknown as ToZod<GetV1HealthQueryResponse>