/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1Assets200, GetV1AssetsQueryResponse } from "../types/GetV1Assets.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const getV1Assets200Schema = z.object({
    "assets": z.array(z.object({
    "id": z.string(),
"name": z.string(),
"pastel": z.enum(["peach", "mint", "sky", "lilac"]),
"price_usd": z.union([z.number(), z.null()]),
"change_24h_pct": z.union([z.number(), z.null()]),
"cached_at": z.union([z.number(), z.null()])
    }))
    }) as unknown as ToZod<GetV1Assets200>

export const getV1AssetsQueryResponseSchema = getV1Assets200Schema as unknown as ToZod<GetV1AssetsQueryResponse>