/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1PushVapidKey200, GetV1PushVapidKeyQueryResponse } from "../types/GetV1PushVapidKey.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const getV1PushVapidKey200Schema = z.object({
    "vapid_public_key": z.string()
    }) as unknown as ToZod<GetV1PushVapidKey200>

export const getV1PushVapidKeyQueryResponseSchema = getV1PushVapidKey200Schema as unknown as ToZod<GetV1PushVapidKeyQueryResponse>