/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1HandlesCheckQueryParams, GetV1HandlesCheck200, GetV1HandlesCheckQueryResponse } from "../types/GetV1HandlesCheck.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

export const getV1HandlesCheckQueryParamsSchema = z.object({
    "handle": z.string().min(1).max(40)
    }) as unknown as ToZod<GetV1HandlesCheckQueryParams>

/**
 * @description Default Response
 */
export const getV1HandlesCheck200Schema = z.object({
    "available": z.boolean(),
"reason": z.union([z.enum(["invalid_format", "reserved", "taken"]), z.null()])
    }) as unknown as ToZod<GetV1HandlesCheck200>

export const getV1HandlesCheckQueryResponseSchema = getV1HandlesCheck200Schema as unknown as ToZod<GetV1HandlesCheckQueryResponse>