/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1DailyQuestion200, GetV1DailyQuestionQueryResponse } from "../types/GetV1DailyQuestion.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const getV1DailyQuestion200Schema = z.object({
    "question": z.union([z.object({
    "id": z.uuid(),
"date": z.string(),
"asset_id": z.string(),
"direction_resolved": z.union([z.enum(["up", "down", "tie"]), z.null()]),
"resolved_at": z.union([z.string(), z.null()]),
"created_at": z.string()
    }), z.null()]),
"my_prediction": z.union([z.object({
    "direction": z.enum(["up", "down"]),
"stake": z.number(),
"status": z.enum(["pending", "correct", "wrong", "tie"]),
"payout": z.union([z.number(), z.null()])
    }), z.null()]),
"points_balance": z.int().min(-9007199254740991).max(9007199254740991)
    }) as unknown as ToZod<GetV1DailyQuestion200>

export const getV1DailyQuestionQueryResponseSchema = getV1DailyQuestion200Schema as unknown as ToZod<GetV1DailyQuestionQueryResponse>