/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1LearnState200, GetV1LearnStateQueryResponse } from "../types/GetV1LearnState.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const getV1LearnState200Schema = z.object({
    "tracks": z.array(z.object({
    "id": z.string(),
"title": z.string(),
"lessons_total": z.number(),
"lessons_completed": z.number()
    })),
"lessons": z.array(z.object({
    "id": z.string(),
"track_id": z.string(),
"completed_at": z.union([z.string(), z.null()]),
"quiz_score": z.union([z.number(), z.null()])
    }))
    }) as unknown as ToZod<GetV1LearnState200>

export const getV1LearnStateQueryResponseSchema = getV1LearnState200Schema as unknown as ToZod<GetV1LearnStateQueryResponse>