/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1Me200, GetV1Me404, GetV1MeQueryResponse } from "../types/GetV1Me.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const getV1Me200Schema = z.object({
    "user": z.object({
    "id": z.uuid(),
"handle": z.union([z.string(), z.null()]),
"avatar": z.union([z.string(), z.null()])
    }),
"portfolio": z.object({
    "cash_usd": z.string(),
"holdings": z.array(z.object({
    "asset_id": z.string(),
"qty": z.string(),
"cost_basis": z.string(),
"price_usd": z.union([z.number(), z.null()]),
"value_usd": z.union([z.string(), z.null()])
    })),
"total_value_usd": z.string()
    })
    }) as unknown as ToZod<GetV1Me200>

/**
 * @description Default Response
 */
export const getV1Me404Schema = z.object({
    "error": z.enum(["user_not_found"])
    }) as unknown as ToZod<GetV1Me404>

export const getV1MeQueryResponseSchema = getV1Me200Schema as unknown as ToZod<GetV1MeQueryResponse>