/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchV1Me200, PatchV1Me400, PatchV1Me404, PatchV1Me409, PatchV1MeMutationRequest, PatchV1MeMutationResponse } from "../types/PatchV1Me.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const patchV1Me200Schema = z.object({
    "user": z.object({
    "id": z.uuid(),
"handle": z.union([z.string(), z.null()]),
"avatar": z.union([z.string(), z.null()])
    })
    }) as unknown as ToZod<PatchV1Me200>

/**
 * @description Default Response
 */
export const patchV1Me400Schema = z.object({
    "error": z.enum(["invalid_handle_format", "handle_reserved", "handle_taken"])
    }) as unknown as ToZod<PatchV1Me400>

/**
 * @description Default Response
 */
export const patchV1Me404Schema = z.object({
    "error": z.enum(["user_not_found"])
    }) as unknown as ToZod<PatchV1Me404>

/**
 * @description Default Response
 */
export const patchV1Me409Schema = z.object({
    "error": z.enum(["invalid_handle_format", "handle_reserved", "handle_taken"])
    }) as unknown as ToZod<PatchV1Me409>

export const patchV1MeMutationRequestSchema = z.object({
    "handle": z.string().min(1).max(40).optional(),
"avatar": z.enum(["peach", "mint", "sky", "lilac"]).optional()
    }) as unknown as ToZod<PatchV1MeMutationRequest>

export const patchV1MeMutationResponseSchema = patchV1Me200Schema as unknown as ToZod<PatchV1MeMutationResponse>