/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1LessonsIdCompletePathParams, PostV1LessonsIdComplete200, PostV1LessonsIdComplete201, PostV1LessonsIdComplete400, PostV1LessonsIdComplete404, PostV1LessonsIdCompleteMutationRequest, PostV1LessonsIdCompleteMutationResponse } from "../types/PostV1LessonsIdComplete.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

export const postV1LessonsIdCompletePathParamsSchema = z.object({
    "id": z.string().min(1)
    }) as unknown as ToZod<PostV1LessonsIdCompletePathParams>

/**
 * @description Default Response
 */
export const postV1LessonsIdComplete200Schema = z.object({
    "progress": z.object({
    "lesson_id": z.string(),
"quiz_score": z.number(),
"completed_at": z.string(),
"updated_at": z.string()
    }),
"is_first_lesson": z.boolean(),
"track_just_completed": z.union([z.enum(["fundamentals", "markets", "safety"]), z.null()])
    }) as unknown as ToZod<PostV1LessonsIdComplete200>

/**
 * @description Default Response
 */
export const postV1LessonsIdComplete201Schema = z.object({
    "progress": z.object({
    "lesson_id": z.string(),
"quiz_score": z.number(),
"completed_at": z.string(),
"updated_at": z.string()
    }),
"is_first_lesson": z.boolean(),
"track_just_completed": z.union([z.enum(["fundamentals", "markets", "safety"]), z.null()])
    }) as unknown as ToZod<PostV1LessonsIdComplete201>

/**
 * @description Default Response
 */
export const postV1LessonsIdComplete400Schema = z.any() as unknown as ToZod<PostV1LessonsIdComplete400>

/**
 * @description Default Response
 */
export const postV1LessonsIdComplete404Schema = z.object({
    "error": z.enum(["lesson_not_found", "invalid_score"])
    }) as unknown as ToZod<PostV1LessonsIdComplete404>

export const postV1LessonsIdCompleteMutationRequestSchema = z.object({
    "quiz_score": z.int().min(0).max(100)
    }) as unknown as ToZod<PostV1LessonsIdCompleteMutationRequest>

export const postV1LessonsIdCompleteMutationResponseSchema = z.union([postV1LessonsIdComplete200Schema, postV1LessonsIdComplete201Schema]) as unknown as ToZod<PostV1LessonsIdCompleteMutationResponse>