/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1PushSubscribe204, PostV1PushSubscribeMutationRequest, PostV1PushSubscribeMutationResponse } from "../types/PostV1PushSubscribe.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postV1PushSubscribe204Schema = z.any() as unknown as ToZod<PostV1PushSubscribe204>

export const postV1PushSubscribeMutationRequestSchema = z.object({
    "endpoint": z.url(),
"p256dh": z.string().min(1),
"auth": z.string().min(1)
    }) as unknown as ToZod<PostV1PushSubscribeMutationRequest>

export const postV1PushSubscribeMutationResponseSchema = postV1PushSubscribe204Schema as unknown as ToZod<PostV1PushSubscribeMutationResponse>