/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1AuthDevice200, PostV1AuthDeviceMutationRequest, PostV1AuthDeviceMutationResponse } from "../types/PostV1AuthDevice.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postV1AuthDevice200Schema = z.object({
    "access_token": z.string(),
"refresh_token": z.string(),
"user": z.object({
    "id": z.uuid(),
"handle": z.union([z.string(), z.null()])
    })
    }) as unknown as ToZod<PostV1AuthDevice200>

export const postV1AuthDeviceMutationRequestSchema = z.object({
    "device_uuid": z.uuid()
    }) as unknown as ToZod<PostV1AuthDeviceMutationRequest>

export const postV1AuthDeviceMutationResponseSchema = postV1AuthDevice200Schema as unknown as ToZod<PostV1AuthDeviceMutationResponse>