/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1AuthRefresh200, PostV1AuthRefresh401, PostV1AuthRefreshMutationRequest, PostV1AuthRefreshMutationResponse } from "../types/PostV1AuthRefresh.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postV1AuthRefresh200Schema = z.object({
    "access_token": z.string(),
"refresh_token": z.string()
    }) as unknown as ToZod<PostV1AuthRefresh200>

/**
 * @description Default Response
 */
export const postV1AuthRefresh401Schema = z.object({
    "error": z.enum(["invalid_refresh_token"])
    }) as unknown as ToZod<PostV1AuthRefresh401>

export const postV1AuthRefreshMutationRequestSchema = z.object({
    "refresh_token": z.string().min(20)
    }) as unknown as ToZod<PostV1AuthRefreshMutationRequest>

export const postV1AuthRefreshMutationResponseSchema = postV1AuthRefresh200Schema as unknown as ToZod<PostV1AuthRefreshMutationResponse>