/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1Trades200, PostV1Trades201, PostV1Trades400, PostV1Trades422, PostV1Trades429, PostV1Trades503, PostV1TradesMutationRequest, PostV1TradesMutationResponse } from "../types/PostV1Trades.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postV1Trades200Schema = z.object({
    "trade": z.object({
    "id": z.uuid(),
"asset_id": z.string(),
"side": z.enum(["buy", "sell"]),
"usd_amount": z.string(),
"qty": z.string(),
"price_at_execution": z.string(),
"idempotency_key": z.string(),
"created_at": z.string()
    }),
"is_first_trade": z.boolean()
    }) as unknown as ToZod<PostV1Trades200>

/**
 * @description Default Response
 */
export const postV1Trades201Schema = z.object({
    "trade": z.object({
    "id": z.uuid(),
"asset_id": z.string(),
"side": z.enum(["buy", "sell"]),
"usd_amount": z.string(),
"qty": z.string(),
"price_at_execution": z.string(),
"idempotency_key": z.string(),
"created_at": z.string()
    }),
"is_first_trade": z.boolean()
    }) as unknown as ToZod<PostV1Trades201>

/**
 * @description Default Response
 */
export const postV1Trades400Schema = z.any() as unknown as ToZod<PostV1Trades400>

/**
 * @description Default Response
 */
export const postV1Trades422Schema = z.object({
    "error": z.enum(["insufficient_cash", "insufficient_qty", "unknown_asset", "invalid_amount"])
    }) as unknown as ToZod<PostV1Trades422>

/**
 * @description Default Response
 */
export const postV1Trades429Schema = z.any() as unknown as ToZod<PostV1Trades429>

/**
 * @description Default Response
 */
export const postV1Trades503Schema = z.object({
    "error": z.enum(["price_unavailable"])
    }) as unknown as ToZod<PostV1Trades503>

export const postV1TradesMutationRequestSchema = z.object({
    "asset_id": z.enum(["BTC", "ETH", "SOL", "USDC", "BNB", "XRP", "ADA", "DOGE", "AVAX", "LINK", "DOT", "TON"]),
"side": z.enum(["buy", "sell"]),
"usd_amount": z.string().regex(/^\d+(\.\d{1,8})?$/),
"idempotency_key": z.string().min(1).max(120)
    }) as unknown as ToZod<PostV1TradesMutationRequest>

export const postV1TradesMutationResponseSchema = z.union([postV1Trades200Schema, postV1Trades201Schema]) as unknown as ToZod<PostV1TradesMutationResponse>