/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1PushUnsubscribe204, PostV1PushUnsubscribeMutationRequest, PostV1PushUnsubscribeMutationResponse } from "../types/PostV1PushUnsubscribe.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postV1PushUnsubscribe204Schema = z.any() as unknown as ToZod<PostV1PushUnsubscribe204>

export const postV1PushUnsubscribeMutationRequestSchema = z.object({
    "endpoint": z.url()
    }) as unknown as ToZod<PostV1PushUnsubscribeMutationRequest>

export const postV1PushUnsubscribeMutationResponseSchema = postV1PushUnsubscribe204Schema as unknown as ToZod<PostV1PushUnsubscribeMutationResponse>