/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1Predictions200, PostV1Predictions201, PostV1Predictions400, PostV1Predictions422, PostV1Predictions429, PostV1PredictionsMutationRequest, PostV1PredictionsMutationResponse } from "../types/PostV1Predictions.ts";
import type { ToZod } from "@kubb/plugin-zod/utils/v4";
import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postV1Predictions200Schema = z.object({
    "prediction": z.object({
    "id": z.uuid(),
"direction": z.string(),
"stake": z.number(),
"status": z.string(),
"payout": z.union([z.number(), z.null()]),
"created_at": z.string()
    }),
"points_balance": z.int().min(-9007199254740991).max(9007199254740991)
    }) as unknown as ToZod<PostV1Predictions200>

/**
 * @description Default Response
 */
export const postV1Predictions201Schema = z.object({
    "prediction": z.object({
    "id": z.uuid(),
"direction": z.string(),
"stake": z.number(),
"status": z.string(),
"payout": z.union([z.number(), z.null()]),
"created_at": z.string()
    }),
"points_balance": z.int().min(-9007199254740991).max(9007199254740991)
    }) as unknown as ToZod<PostV1Predictions201>

/**
 * @description Default Response
 */
export const postV1Predictions400Schema = z.any() as unknown as ToZod<PostV1Predictions400>

/**
 * @description Default Response
 */
export const postV1Predictions422Schema = z.object({
    "error": z.enum(["question_not_found", "question_resolved", "invalid_direction", "invalid_stake", "insufficient_points"])
    }) as unknown as ToZod<PostV1Predictions422>

/**
 * @description Default Response
 */
export const postV1Predictions429Schema = z.any() as unknown as ToZod<PostV1Predictions429>

export const postV1PredictionsMutationRequestSchema = z.object({
    "daily_question_id": z.uuid(),
"direction": z.enum(["up", "down"]),
"stake": z.int().min(100).max(500),
"idempotency_key": z.string().min(1).max(120)
    }) as unknown as ToZod<PostV1PredictionsMutationRequest>

export const postV1PredictionsMutationResponseSchema = z.union([postV1Predictions200Schema, postV1Predictions201Schema]) as unknown as ToZod<PostV1PredictionsMutationResponse>