/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1AssetsQueryResponse } from "../types/GetV1Assets.ts";

function getGetV1AssetsUrl() {
  const res = { method: 'GET', url: `/v1/assets` as const }  
  return res
}

/**
 * @summary Asset roster with current prices
 * {@link /v1/assets}
 */
export async function getV1Assets(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1AssetsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1AssetsUrl().url.toString(), ... requestConfig })  
  return res.data
}