/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1TradesQueryResponse, GetV1TradesQueryParams } from "../types/GetV1Trades.ts";

function getGetV1TradesUrl() {
  const res = { method: 'GET', url: `/v1/trades` as const }  
  return res
}

/**
 * @summary List the user's trades, newest first
 * {@link /v1/trades}
 */
export async function getV1Trades(params?: GetV1TradesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1TradesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1TradesUrl().url.toString(), params, ... requestConfig })  
  return res.data
}