/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1LearnStateQueryResponse } from "../types/GetV1LearnState.ts";

function getGetV1LearnStateUrl() {
  const res = { method: 'GET', url: `/v1/learn/state` as const }  
  return res
}

/**
 * @summary Full curriculum state with per-user completion
 * {@link /v1/learn/state}
 */
export async function getV1LearnState(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1LearnStateQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1LearnStateUrl().url.toString(), ... requestConfig })  
  return res.data
}