/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1DailyQuestionQueryResponse } from "../types/GetV1DailyQuestion.ts";

function getGetV1DailyQuestionUrl() {
  const res = { method: 'GET', url: `/v1/daily-question` as const }  
  return res
}

/**
 * @summary Get today's market question + the user's prediction (if any)
 * {@link /v1/daily-question}
 */
export async function getV1DailyQuestion(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1DailyQuestionQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1DailyQuestionUrl().url.toString(), ... requestConfig })  
  return res.data
}