/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1LeaderboardQueryResponse, GetV1LeaderboardQueryParams } from "../types/GetV1Leaderboard.ts";

function getGetV1LeaderboardUrl() {
  const res = { method: 'GET', url: `/v1/leaderboard` as const }  
  return res
}

/**
 * @summary Get the global weekly leaderboard (top N + caller's rank)
 * {@link /v1/leaderboard}
 */
export async function getV1Leaderboard(params?: GetV1LeaderboardQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1LeaderboardQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1LeaderboardUrl().url.toString(), params, ... requestConfig })  
  return res.data
}