/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1HandlesCheckQueryResponse, GetV1HandlesCheckQueryParams } from "../types/GetV1HandlesCheck.ts";

function getGetV1HandlesCheckUrl() {
  const res = { method: 'GET', url: `/v1/handles/check` as const }  
  return res
}

/**
 * @summary Check whether a handle is available
 * {@link /v1/handles/check}
 */
export async function getV1HandlesCheck(params: GetV1HandlesCheckQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1HandlesCheckQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1HandlesCheckUrl().url.toString(), params, ... requestConfig })  
  return res.data
}