/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1PushVapidKeyQueryResponse } from "../types/GetV1PushVapidKey.ts";

function getGetV1PushVapidKeyUrl() {
  const res = { method: 'GET', url: `/v1/push/vapid-key` as const }  
  return res
}

/**
 * @summary VAPID public key
 * {@link /v1/push/vapid-key}
 */
export async function getV1PushVapidKey(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1PushVapidKeyQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1PushVapidKeyUrl().url.toString(), ... requestConfig })  
  return res.data
}