/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1HealthQueryResponse } from "../types/GetV1Health.ts";

function getGetV1HealthUrl() {
  const res = { method: 'GET', url: `/v1/health` as const }  
  return res
}

/**
 * @summary Liveness probe
 * {@link /v1/health}
 */
export async function getV1Health(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1HealthQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetV1HealthUrl().url.toString(), ... requestConfig })  
  return res.data
}