/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PatchV1MeMutationRequest, PatchV1MeMutationResponse, PatchV1Me400, PatchV1Me404, PatchV1Me409 } from "../types/PatchV1Me.ts";

function getPatchV1MeUrl() {
  const res = { method: 'PATCH', url: `/v1/me` as const }  
  return res
}

/**
 * @summary Update current user's handle and/or avatar
 * {@link /v1/me}
 */
export async function patchV1Me(data?: PatchV1MeMutationRequest, config: Partial<RequestConfig<PatchV1MeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PatchV1MeMutationResponse, ResponseErrorConfig<PatchV1Me400 | PatchV1Me404 | PatchV1Me409>, PatchV1MeMutationRequest>({ method : "PATCH", url : getPatchV1MeUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}