/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1AuthDeviceMutationRequest, PostV1AuthDeviceMutationResponse } from "../types/PostV1AuthDevice.ts";

function getPostV1AuthDeviceUrl() {
  const res = { method: 'POST', url: `/v1/auth/device` as const }  
  return res
}

/**
 * @summary Authenticate a device, creating a user on first call
 * {@link /v1/auth/device}
 */
export async function postV1AuthDevice(data: PostV1AuthDeviceMutationRequest, config: Partial<RequestConfig<PostV1AuthDeviceMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1AuthDeviceMutationResponse, ResponseErrorConfig<Error>, PostV1AuthDeviceMutationRequest>({ method : "POST", url : getPostV1AuthDeviceUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}