/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1AuthRefreshMutationRequest, PostV1AuthRefreshMutationResponse, PostV1AuthRefresh401 } from "../types/PostV1AuthRefresh.ts";

function getPostV1AuthRefreshUrl() {
  const res = { method: 'POST', url: `/v1/auth/refresh` as const }  
  return res
}

/**
 * @summary Rotate a refresh token
 * {@link /v1/auth/refresh}
 */
export async function postV1AuthRefresh(data: PostV1AuthRefreshMutationRequest, config: Partial<RequestConfig<PostV1AuthRefreshMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1AuthRefreshMutationResponse, ResponseErrorConfig<PostV1AuthRefresh401>, PostV1AuthRefreshMutationRequest>({ method : "POST", url : getPostV1AuthRefreshUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}