/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1PushSubscribeMutationRequest, PostV1PushSubscribeMutationResponse } from "../types/PostV1PushSubscribe.ts";

function getPostV1PushSubscribeUrl() {
  const res = { method: 'POST', url: `/v1/push/subscribe` as const }  
  return res
}

/**
 * @summary Subscribe to push notifications
 * {@link /v1/push/subscribe}
 */
export async function postV1PushSubscribe(data: PostV1PushSubscribeMutationRequest, config: Partial<RequestConfig<PostV1PushSubscribeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1PushSubscribeMutationResponse, ResponseErrorConfig<Error>, PostV1PushSubscribeMutationRequest>({ method : "POST", url : getPostV1PushSubscribeUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}