/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1PredictionsMutationRequest, PostV1PredictionsMutationResponse, PostV1Predictions400, PostV1Predictions422, PostV1Predictions429 } from "../types/PostV1Predictions.ts";

function getPostV1PredictionsUrl() {
  const res = { method: 'POST', url: `/v1/predictions` as const }  
  return res
}

/**
 * @summary Submit a direction prediction for today's daily question
 * {@link /v1/predictions}
 */
export async function postV1Predictions(data: PostV1PredictionsMutationRequest, config: Partial<RequestConfig<PostV1PredictionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1PredictionsMutationResponse, ResponseErrorConfig<PostV1Predictions400 | PostV1Predictions422 | PostV1Predictions429>, PostV1PredictionsMutationRequest>({ method : "POST", url : getPostV1PredictionsUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}