/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1LessonsIdCompleteMutationRequest, PostV1LessonsIdCompleteMutationResponse, PostV1LessonsIdCompletePathParams, PostV1LessonsIdComplete400, PostV1LessonsIdComplete404 } from "../types/PostV1LessonsIdComplete.ts";

function getPostV1LessonsIdCompleteUrl(id: PostV1LessonsIdCompletePathParams["id"]) {
  const res = { method: 'POST', url: `/v1/lessons/${id}/complete` as const }  
  return res
}

/**
 * @summary Mark a lesson complete; idempotent on repeat
 * {@link /v1/lessons/:id/complete}
 */
export async function postV1LessonsIdComplete(id: PostV1LessonsIdCompletePathParams["id"], data: PostV1LessonsIdCompleteMutationRequest, config: Partial<RequestConfig<PostV1LessonsIdCompleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1LessonsIdCompleteMutationResponse, ResponseErrorConfig<PostV1LessonsIdComplete400 | PostV1LessonsIdComplete404>, PostV1LessonsIdCompleteMutationRequest>({ method : "POST", url : getPostV1LessonsIdCompleteUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}