/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1TradesMutationRequest, PostV1TradesMutationResponse, PostV1Trades400, PostV1Trades422, PostV1Trades429, PostV1Trades503 } from "../types/PostV1Trades.ts";

function getPostV1TradesUrl() {
  const res = { method: 'POST', url: `/v1/trades` as const }  
  return res
}

/**
 * @summary Execute one buy/sell at the cached price
 * {@link /v1/trades}
 */
export async function postV1Trades(data: PostV1TradesMutationRequest, config: Partial<RequestConfig<PostV1TradesMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1TradesMutationResponse, ResponseErrorConfig<PostV1Trades400 | PostV1Trades422 | PostV1Trades429 | PostV1Trades503>, PostV1TradesMutationRequest>({ method : "POST", url : getPostV1TradesUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}