/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1PushUnsubscribeMutationRequest, PostV1PushUnsubscribeMutationResponse } from "../types/PostV1PushUnsubscribe.ts";

function getPostV1PushUnsubscribeUrl() {
  const res = { method: 'POST', url: `/v1/push/unsubscribe` as const }  
  return res
}

/**
 * @summary Unsubscribe from push notifications
 * {@link /v1/push/unsubscribe}
 */
export async function postV1PushUnsubscribe(data: PostV1PushUnsubscribeMutationRequest, config: Partial<RequestConfig<PostV1PushUnsubscribeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1PushUnsubscribeMutationResponse, ResponseErrorConfig<Error>, PostV1PushUnsubscribeMutationRequest>({ method : "POST", url : getPostV1PushUnsubscribeUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}