/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingLessonRouteImport } from './routes/onboarding/lesson'
import { Route as OnboardingHandleRouteImport } from './routes/onboarding/handle'
import { Route as OnboardingBalanceRouteImport } from './routes/onboarding/balance'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingLessonRoute = OnboardingLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHandleRoute = OnboardingHandleRouteImport.update({
  id: '/handle',
  path: '/handle',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingBalanceRoute = OnboardingBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/trade': typeof TradeRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/onboarding/balance': typeof OnboardingBalanceRoute
  '/onboarding/handle': typeof OnboardingHandleRoute
  '/onboarding/lesson': typeof OnboardingLessonRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/trade': typeof TradeRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/onboarding/balance': typeof OnboardingBalanceRoute
  '/onboarding/handle': typeof OnboardingHandleRoute
  '/onboarding/lesson': typeof OnboardingLessonRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/trade': typeof TradeRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/onboarding/balance': typeof OnboardingBalanceRoute
  '/onboarding/handle': typeof OnboardingHandleRoute
  '/onboarding/lesson': typeof OnboardingLessonRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/learn'
    | '/trade'
    | '/learn/$lessonId'
    | '/onboarding/balance'
    | '/onboarding/handle'
    | '/onboarding/lesson'
    | '/onboarding/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/learn'
    | '/trade'
    | '/learn/$lessonId'
    | '/onboarding/balance'
    | '/onboarding/handle'
    | '/onboarding/lesson'
    | '/onboarding/welcome'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/learn'
    | '/trade'
    | '/learn/$lessonId'
    | '/onboarding/balance'
    | '/onboarding/handle'
    | '/onboarding/lesson'
    | '/onboarding/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRouteWithChildren
  TradeRoute: typeof TradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/lesson': {
      id: '/onboarding/lesson'
      path: '/lesson'
      fullPath: '/onboarding/lesson'
      preLoaderRoute: typeof OnboardingLessonRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/handle': {
      id: '/onboarding/handle'
      path: '/handle'
      fullPath: '/onboarding/handle'
      preLoaderRoute: typeof OnboardingHandleRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/balance': {
      id: '/onboarding/balance'
      path: '/balance'
      fullPath: '/onboarding/balance'
      preLoaderRoute: typeof OnboardingBalanceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingBalanceRoute: typeof OnboardingBalanceRoute
  OnboardingHandleRoute: typeof OnboardingHandleRoute
  OnboardingLessonRoute: typeof OnboardingLessonRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingBalanceRoute: OnboardingBalanceRoute,
  OnboardingHandleRoute: OnboardingHandleRoute,
  OnboardingLessonRoute: OnboardingLessonRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface LearnRouteChildren {
  LearnLessonIdRoute: typeof LearnLessonIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnLessonIdRoute: LearnLessonIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRouteWithChildren,
  TradeRoute: TradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
