/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1PushVapidKeyQueryResponse } from "../types/GetV1PushVapidKey.ts";
import { http } from "msw";

export function getV1PushVapidKeyHandler(data?: GetV1PushVapidKeyQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response)) {
  return http.get('/v1/push/vapid-key', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}