/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetV1DailyQuestionQueryResponse } from "../types/GetV1DailyQuestion.ts";
import { http } from "msw";

export function getV1DailyQuestionHandler(data?: GetV1DailyQuestionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response)) {
  return http.get('/v1/daily-question', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}