/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getV1AssetsHandler } from "./getV1AssetsHandler.ts";
import { getV1HandlesCheckHandler } from "./getV1HandlesCheckHandler.ts";
import { getV1HealthHandler } from "./getV1HealthHandler.ts";
import { getV1MeHandler } from "./getV1MeHandler.ts";
import { getV1TradesHandler } from "./getV1TradesHandler.ts";
import { patchV1MeHandler } from "./patchV1MeHandler.ts";
import { postV1AuthDeviceHandler } from "./postV1AuthDeviceHandler.ts";
import { postV1AuthRefreshHandler } from "./postV1AuthRefreshHandler.ts";
import { postV1TradesHandler } from "./postV1TradesHandler.ts";

export const handlers = [getV1HealthHandler(),postV1AuthDeviceHandler(),postV1AuthRefreshHandler(),getV1AssetsHandler(),getV1MeHandler(),patchV1MeHandler(),getV1HandlesCheckHandler(),postV1TradesHandler(),getV1TradesHandler()] as const