/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getV1HealthHandler } from "./getV1HealthHandler.ts";
import { postV1AuthDeviceHandler } from "./postV1AuthDeviceHandler.ts";
import { postV1AuthRefreshHandler } from "./postV1AuthRefreshHandler.ts";

export const handlers = [getV1HealthHandler(),postV1AuthDeviceHandler(),postV1AuthRefreshHandler()] as const