/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchV1MeMutationResponse } from "../types/PatchV1Me.ts";
import { http } from "msw";

export function patchV1MeHandler(data?: PatchV1MeMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response)) {
  return http.patch('/v1/me', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}