/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1TradesMutationResponse } from "../types/PostV1Trades.ts";
import { http } from "msw";

export function postV1TradesHandler(data?: PostV1TradesMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response)) {
  return http.post('/v1/trades', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}