/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1PredictionsMutationResponse } from "../types/PostV1Predictions.ts";
import { http } from "msw";

export function postV1PredictionsHandler(data?: PostV1PredictionsMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response)) {
  return http.post('/v1/predictions', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}