/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1LessonsIdCompleteMutationResponse } from "../types/PostV1LessonsIdComplete.ts";
import { http } from "msw";

export function postV1LessonsIdCompleteHandler(data?: PostV1LessonsIdCompleteMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response)) {
  return http.post('/v1/lessons/:id/complete', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}