/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostV1PushSubscribeMutationResponse } from "../types/PostV1PushSubscribe.ts";
import { http } from "msw";

export function postV1PushSubscribeHandler(data?: PostV1PushSubscribeMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response)) {
  return http.post('/v1/push/subscribe', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 204,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}