/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1HealthQueryResponse } from "../types/GetV1Health.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1Health } from "../client/getV1Health.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1HealthSuspenseQueryKey = () => [{ url: '/v1/health' }] as const

export type GetV1HealthSuspenseQueryKey = ReturnType<typeof getV1HealthSuspenseQueryKey>

export function getV1HealthSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1HealthSuspenseQueryKey()
  return queryOptions<GetV1HealthQueryResponse, ResponseErrorConfig<Error>, GetV1HealthQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Health(config)
   },
  })
}

/**
 * @summary Liveness probe
 * {@link /v1/health}
 */
export function useGetV1HealthSuspense<TData = GetV1HealthQueryResponse, TQueryKey extends QueryKey = GetV1HealthSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1HealthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1HealthSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1HealthSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}