/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1DailyQuestionQueryResponse } from "../types/GetV1DailyQuestion.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1DailyQuestion } from "../client/getV1DailyQuestion.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1DailyQuestionSuspenseQueryKey = () => [{ url: '/v1/daily-question' }] as const

export type GetV1DailyQuestionSuspenseQueryKey = ReturnType<typeof getV1DailyQuestionSuspenseQueryKey>

export function getV1DailyQuestionSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1DailyQuestionSuspenseQueryKey()
  return queryOptions<GetV1DailyQuestionQueryResponse, ResponseErrorConfig<Error>, GetV1DailyQuestionQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1DailyQuestion(config)
   },
  })
}

/**
 * @summary Get today's market question + the user's prediction (if any)
 * {@link /v1/daily-question}
 */
export function useGetV1DailyQuestionSuspense<TData = GetV1DailyQuestionQueryResponse, TQueryKey extends QueryKey = GetV1DailyQuestionSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1DailyQuestionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1DailyQuestionSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1DailyQuestionSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}