/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1HealthQueryResponse } from "../types/GetV1Health.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getV1Health } from "../client/getV1Health.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1HealthQueryKey = () => [{ url: '/v1/health' }] as const

export type GetV1HealthQueryKey = ReturnType<typeof getV1HealthQueryKey>

export function getV1HealthQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1HealthQueryKey()
  return queryOptions<GetV1HealthQueryResponse, ResponseErrorConfig<Error>, GetV1HealthQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Health(config)
   },
  })
}

/**
 * @summary Liveness probe
 * {@link /v1/health}
 */
export function useGetV1Health<TData = GetV1HealthQueryResponse, TQueryData = GetV1HealthQueryResponse, TQueryKey extends QueryKey = GetV1HealthQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1HealthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1HealthQueryKey()

  const query = useQuery({
   ...getV1HealthQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}