/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1MeQueryResponse, GetV1Me404, GetV1Me500 } from "../types/GetV1Me.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1Me } from "../client/getV1Me.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1MeSuspenseQueryKey = () => [{ url: '/v1/me' }] as const

export type GetV1MeSuspenseQueryKey = ReturnType<typeof getV1MeSuspenseQueryKey>

export function getV1MeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1MeSuspenseQueryKey()
  return queryOptions<GetV1MeQueryResponse, ResponseErrorConfig<GetV1Me404 | GetV1Me500>, GetV1MeQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Me(config)
   },
  })
}

/**
 * @summary Current user + portfolio with valuation
 * {@link /v1/me}
 */
export function useGetV1MeSuspense<TData = GetV1MeQueryResponse, TQueryKey extends QueryKey = GetV1MeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1MeQueryResponse, ResponseErrorConfig<GetV1Me404 | GetV1Me500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1MeSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1MeSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1Me404 | GetV1Me500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}