/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1PushVapidKeyQueryResponse } from "../types/GetV1PushVapidKey.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getV1PushVapidKey } from "../client/getV1PushVapidKey.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1PushVapidKeyQueryKey = () => [{ url: '/v1/push/vapid-key' }] as const

export type GetV1PushVapidKeyQueryKey = ReturnType<typeof getV1PushVapidKeyQueryKey>

export function getV1PushVapidKeyQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1PushVapidKeyQueryKey()
  return queryOptions<GetV1PushVapidKeyQueryResponse, ResponseErrorConfig<Error>, GetV1PushVapidKeyQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1PushVapidKey(config)
   },
  })
}

/**
 * @summary VAPID public key
 * {@link /v1/push/vapid-key}
 */
export function useGetV1PushVapidKey<TData = GetV1PushVapidKeyQueryResponse, TQueryData = GetV1PushVapidKeyQueryResponse, TQueryKey extends QueryKey = GetV1PushVapidKeyQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1PushVapidKeyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1PushVapidKeyQueryKey()

  const query = useQuery({
   ...getV1PushVapidKeyQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}