/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1LearnStateQueryResponse } from "../types/GetV1LearnState.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1LearnState } from "../client/getV1LearnState.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1LearnStateSuspenseQueryKey = () => [{ url: '/v1/learn/state' }] as const

export type GetV1LearnStateSuspenseQueryKey = ReturnType<typeof getV1LearnStateSuspenseQueryKey>

export function getV1LearnStateSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1LearnStateSuspenseQueryKey()
  return queryOptions<GetV1LearnStateQueryResponse, ResponseErrorConfig<Error>, GetV1LearnStateQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1LearnState(config)
   },
  })
}

/**
 * @summary Full curriculum state with per-user completion
 * {@link /v1/learn/state}
 */
export function useGetV1LearnStateSuspense<TData = GetV1LearnStateQueryResponse, TQueryKey extends QueryKey = GetV1LearnStateSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1LearnStateQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1LearnStateSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1LearnStateSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}