/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1DailyQuestionQueryResponse } from "../types/GetV1DailyQuestion.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getV1DailyQuestion } from "../client/getV1DailyQuestion.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1DailyQuestionQueryKey = () => [{ url: '/v1/daily-question' }] as const

export type GetV1DailyQuestionQueryKey = ReturnType<typeof getV1DailyQuestionQueryKey>

export function getV1DailyQuestionQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1DailyQuestionQueryKey()
  return queryOptions<GetV1DailyQuestionQueryResponse, ResponseErrorConfig<Error>, GetV1DailyQuestionQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1DailyQuestion(config)
   },
  })
}

/**
 * @summary Get today's market question + the user's prediction (if any)
 * {@link /v1/daily-question}
 */
export function useGetV1DailyQuestion<TData = GetV1DailyQuestionQueryResponse, TQueryData = GetV1DailyQuestionQueryResponse, TQueryKey extends QueryKey = GetV1DailyQuestionQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1DailyQuestionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1DailyQuestionQueryKey()

  const query = useQuery({
   ...getV1DailyQuestionQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}