/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1TradesQueryResponse, GetV1TradesQueryParams } from "../types/GetV1Trades.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1Trades } from "../client/getV1Trades.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1TradesSuspenseQueryKey = (params?: GetV1TradesQueryParams) => [{ url: '/v1/trades' }, ...(params ? [params] : [])] as const

export type GetV1TradesSuspenseQueryKey = ReturnType<typeof getV1TradesSuspenseQueryKey>

export function getV1TradesSuspenseQueryOptions(params?: GetV1TradesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1TradesSuspenseQueryKey(params)
  return queryOptions<GetV1TradesQueryResponse, ResponseErrorConfig<Error>, GetV1TradesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Trades(params, config)
   },
  })
}

/**
 * @summary List the user's trades, newest first
 * {@link /v1/trades}
 */
export function useGetV1TradesSuspense<TData = GetV1TradesQueryResponse, TQueryKey extends QueryKey = GetV1TradesSuspenseQueryKey>(params?: GetV1TradesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1TradesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1TradesSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getV1TradesSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}