/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1MeQueryResponse, GetV1Me404 } from "../types/GetV1Me.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getV1Me } from "../client/getV1Me.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1MeQueryKey = () => [{ url: '/v1/me' }] as const

export type GetV1MeQueryKey = ReturnType<typeof getV1MeQueryKey>

export function getV1MeQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1MeQueryKey()
  return queryOptions<GetV1MeQueryResponse, ResponseErrorConfig<GetV1Me404>, GetV1MeQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Me(config)
   },
  })
}

/**
 * @summary Current user + portfolio with valuation
 * {@link /v1/me}
 */
export function useGetV1Me<TData = GetV1MeQueryResponse, TQueryData = GetV1MeQueryResponse, TQueryKey extends QueryKey = GetV1MeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1MeQueryResponse, ResponseErrorConfig<GetV1Me404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1MeQueryKey()

  const query = useQuery({
   ...getV1MeQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1Me404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}