/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1AssetsQueryResponse } from "../types/GetV1Assets.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getV1Assets } from "../client/getV1Assets.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1AssetsQueryKey = () => [{ url: '/v1/assets' }] as const

export type GetV1AssetsQueryKey = ReturnType<typeof getV1AssetsQueryKey>

export function getV1AssetsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1AssetsQueryKey()
  return queryOptions<GetV1AssetsQueryResponse, ResponseErrorConfig<Error>, GetV1AssetsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Assets(config)
   },
  })
}

/**
 * @summary Asset roster with current prices
 * {@link /v1/assets}
 */
export function useGetV1Assets<TData = GetV1AssetsQueryResponse, TQueryData = GetV1AssetsQueryResponse, TQueryKey extends QueryKey = GetV1AssetsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1AssetsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1AssetsQueryKey()

  const query = useQuery({
   ...getV1AssetsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}