/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1PushVapidKeyQueryResponse } from "../types/GetV1PushVapidKey.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1PushVapidKey } from "../client/getV1PushVapidKey.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1PushVapidKeySuspenseQueryKey = () => [{ url: '/v1/push/vapid-key' }] as const

export type GetV1PushVapidKeySuspenseQueryKey = ReturnType<typeof getV1PushVapidKeySuspenseQueryKey>

export function getV1PushVapidKeySuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1PushVapidKeySuspenseQueryKey()
  return queryOptions<GetV1PushVapidKeyQueryResponse, ResponseErrorConfig<Error>, GetV1PushVapidKeyQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1PushVapidKey(config)
   },
  })
}

/**
 * @summary VAPID public key
 * {@link /v1/push/vapid-key}
 */
export function useGetV1PushVapidKeySuspense<TData = GetV1PushVapidKeyQueryResponse, TQueryKey extends QueryKey = GetV1PushVapidKeySuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1PushVapidKeyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1PushVapidKeySuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1PushVapidKeySuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}