/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1LeaderboardQueryResponse, GetV1LeaderboardQueryParams } from "../types/GetV1Leaderboard.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1Leaderboard } from "../client/getV1Leaderboard.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1LeaderboardSuspenseQueryKey = (params?: GetV1LeaderboardQueryParams) => [{ url: '/v1/leaderboard' }, ...(params ? [params] : [])] as const

export type GetV1LeaderboardSuspenseQueryKey = ReturnType<typeof getV1LeaderboardSuspenseQueryKey>

export function getV1LeaderboardSuspenseQueryOptions(params?: GetV1LeaderboardQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1LeaderboardSuspenseQueryKey(params)
  return queryOptions<GetV1LeaderboardQueryResponse, ResponseErrorConfig<Error>, GetV1LeaderboardQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Leaderboard(params, config)
   },
  })
}

/**
 * @summary Get the global weekly leaderboard (top N + caller's rank)
 * {@link /v1/leaderboard}
 */
export function useGetV1LeaderboardSuspense<TData = GetV1LeaderboardQueryResponse, TQueryKey extends QueryKey = GetV1LeaderboardSuspenseQueryKey>(params?: GetV1LeaderboardQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1LeaderboardQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1LeaderboardSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getV1LeaderboardSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}