/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1LearnStateQueryResponse } from "../types/GetV1LearnState.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getV1LearnState } from "../client/getV1LearnState.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1LearnStateQueryKey = () => [{ url: '/v1/learn/state' }] as const

export type GetV1LearnStateQueryKey = ReturnType<typeof getV1LearnStateQueryKey>

export function getV1LearnStateQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1LearnStateQueryKey()
  return queryOptions<GetV1LearnStateQueryResponse, ResponseErrorConfig<Error>, GetV1LearnStateQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1LearnState(config)
   },
  })
}

/**
 * @summary Full curriculum state with per-user completion
 * {@link /v1/learn/state}
 */
export function useGetV1LearnState<TData = GetV1LearnStateQueryResponse, TQueryData = GetV1LearnStateQueryResponse, TQueryKey extends QueryKey = GetV1LearnStateQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1LearnStateQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1LearnStateQueryKey()

  const query = useQuery({
   ...getV1LearnStateQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}