/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1AssetsQueryResponse } from "../types/GetV1Assets.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1Assets } from "../client/getV1Assets.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1AssetsSuspenseQueryKey = () => [{ url: '/v1/assets' }] as const

export type GetV1AssetsSuspenseQueryKey = ReturnType<typeof getV1AssetsSuspenseQueryKey>

export function getV1AssetsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1AssetsSuspenseQueryKey()
  return queryOptions<GetV1AssetsQueryResponse, ResponseErrorConfig<Error>, GetV1AssetsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Assets(config)
   },
  })
}

/**
 * @summary Asset roster with current prices
 * {@link /v1/assets}
 */
export function useGetV1AssetsSuspense<TData = GetV1AssetsQueryResponse, TQueryKey extends QueryKey = GetV1AssetsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1AssetsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1AssetsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1AssetsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}