/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { GetV1HandlesCheckQueryResponse, GetV1HandlesCheckQueryParams } from "../types/GetV1HandlesCheck.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getV1HandlesCheck } from "../client/getV1HandlesCheck.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1HandlesCheckSuspenseQueryKey = (params: GetV1HandlesCheckQueryParams) => [{ url: '/v1/handles/check' }, ...(params ? [params] : [])] as const

export type GetV1HandlesCheckSuspenseQueryKey = ReturnType<typeof getV1HandlesCheckSuspenseQueryKey>

export function getV1HandlesCheckSuspenseQueryOptions(params: GetV1HandlesCheckQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1HandlesCheckSuspenseQueryKey(params)
  return queryOptions<GetV1HandlesCheckQueryResponse, ResponseErrorConfig<Error>, GetV1HandlesCheckQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1HandlesCheck(params, config)
   },
  })
}

/**
 * @summary Check whether a handle is available
 * {@link /v1/handles/check}
 */
export function useGetV1HandlesCheckSuspense<TData = GetV1HandlesCheckQueryResponse, TQueryKey extends QueryKey = GetV1HandlesCheckSuspenseQueryKey>(params: GetV1HandlesCheckQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1HandlesCheckQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1HandlesCheckSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getV1HandlesCheckSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}