/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostV1AuthDeviceMutationRequest, PostV1AuthDeviceMutationResponse } from "../types/PostV1AuthDevice.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1AuthDevice } from "../client/postV1AuthDevice.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1AuthDeviceMutationKey = () => [{ url: '/v1/auth/device' }] as const

export type PostV1AuthDeviceMutationKey = ReturnType<typeof postV1AuthDeviceMutationKey>

/**
 * @summary Authenticate a device, creating a user on first call
 * {@link /v1/auth/device}
 */
export function usePostV1AuthDevice<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1AuthDeviceMutationResponse, ResponseErrorConfig<Error>, {data: PostV1AuthDeviceMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1AuthDeviceMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1AuthDeviceMutationKey()

  return useMutation<PostV1AuthDeviceMutationResponse, ResponseErrorConfig<Error>, {data: PostV1AuthDeviceMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1AuthDevice(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}