/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1PushUnsubscribeMutationRequest, PostV1PushUnsubscribeMutationResponse } from "../types/PostV1PushUnsubscribe.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1PushUnsubscribe } from "../client/postV1PushUnsubscribe.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1PushUnsubscribeMutationKey = () => [{ url: '/v1/push/unsubscribe' }] as const

export type PostV1PushUnsubscribeMutationKey = ReturnType<typeof postV1PushUnsubscribeMutationKey>

/**
 * @summary Unsubscribe from push notifications
 * {@link /v1/push/unsubscribe}
 */
export function usePostV1PushUnsubscribe<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1PushUnsubscribeMutationResponse, ResponseErrorConfig<Error>, {data: PostV1PushUnsubscribeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1PushUnsubscribeMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1PushUnsubscribeMutationKey()

  return useMutation<PostV1PushUnsubscribeMutationResponse, ResponseErrorConfig<Error>, {data: PostV1PushUnsubscribeMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1PushUnsubscribe(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}