/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1PushSubscribeMutationRequest, PostV1PushSubscribeMutationResponse } from "../types/PostV1PushSubscribe.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1PushSubscribe } from "../client/postV1PushSubscribe.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1PushSubscribeMutationKey = () => [{ url: '/v1/push/subscribe' }] as const

export type PostV1PushSubscribeMutationKey = ReturnType<typeof postV1PushSubscribeMutationKey>

/**
 * @summary Subscribe to push notifications
 * {@link /v1/push/subscribe}
 */
export function usePostV1PushSubscribe<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1PushSubscribeMutationResponse, ResponseErrorConfig<Error>, {data: PostV1PushSubscribeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1PushSubscribeMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1PushSubscribeMutationKey()

  return useMutation<PostV1PushSubscribeMutationResponse, ResponseErrorConfig<Error>, {data: PostV1PushSubscribeMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1PushSubscribe(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}