/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1TradesMutationRequest, PostV1TradesMutationResponse, PostV1Trades400, PostV1Trades422, PostV1Trades429, PostV1Trades503 } from "../types/PostV1Trades.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1Trades } from "../client/postV1Trades.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1TradesMutationKey = () => [{ url: '/v1/trades' }] as const

export type PostV1TradesMutationKey = ReturnType<typeof postV1TradesMutationKey>

/**
 * @summary Execute one buy/sell at the cached price
 * {@link /v1/trades}
 */
export function usePostV1Trades<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1TradesMutationResponse, ResponseErrorConfig<PostV1Trades400 | PostV1Trades422 | PostV1Trades429 | PostV1Trades503>, {data: PostV1TradesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1TradesMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1TradesMutationKey()

  return useMutation<PostV1TradesMutationResponse, ResponseErrorConfig<PostV1Trades400 | PostV1Trades422 | PostV1Trades429 | PostV1Trades503>, {data: PostV1TradesMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1Trades(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}