/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1LessonsIdCompleteMutationRequest, PostV1LessonsIdCompleteMutationResponse, PostV1LessonsIdCompletePathParams, PostV1LessonsIdComplete400, PostV1LessonsIdComplete404 } from "../types/PostV1LessonsIdComplete.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1LessonsIdComplete } from "../client/postV1LessonsIdComplete.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1LessonsIdCompleteMutationKey = () => [{ url: '/v1/lessons/:id/complete' }] as const

export type PostV1LessonsIdCompleteMutationKey = ReturnType<typeof postV1LessonsIdCompleteMutationKey>

/**
 * @summary Mark a lesson complete; idempotent on repeat
 * {@link /v1/lessons/:id/complete}
 */
export function usePostV1LessonsIdComplete<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1LessonsIdCompleteMutationResponse, ResponseErrorConfig<PostV1LessonsIdComplete400 | PostV1LessonsIdComplete404>, {id: PostV1LessonsIdCompletePathParams["id"], data: PostV1LessonsIdCompleteMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1LessonsIdCompleteMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1LessonsIdCompleteMutationKey()

  return useMutation<PostV1LessonsIdCompleteMutationResponse, ResponseErrorConfig<PostV1LessonsIdComplete400 | PostV1LessonsIdComplete404>, {id: PostV1LessonsIdCompletePathParams["id"], data: PostV1LessonsIdCompleteMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1LessonsIdComplete(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}