/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1AuthRefreshMutationRequest, PostV1AuthRefreshMutationResponse, PostV1AuthRefresh401 } from "../types/PostV1AuthRefresh.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1AuthRefresh } from "../client/postV1AuthRefresh.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1AuthRefreshMutationKey = () => [{ url: '/v1/auth/refresh' }] as const

export type PostV1AuthRefreshMutationKey = ReturnType<typeof postV1AuthRefreshMutationKey>

/**
 * @summary Rotate a refresh token
 * {@link /v1/auth/refresh}
 */
export function usePostV1AuthRefresh<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1AuthRefreshMutationResponse, ResponseErrorConfig<PostV1AuthRefresh401>, {data: PostV1AuthRefreshMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1AuthRefreshMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1AuthRefreshMutationKey()

  return useMutation<PostV1AuthRefreshMutationResponse, ResponseErrorConfig<PostV1AuthRefresh401>, {data: PostV1AuthRefreshMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1AuthRefresh(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}