/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PostV1PredictionsMutationRequest, PostV1PredictionsMutationResponse, PostV1Predictions400, PostV1Predictions422, PostV1Predictions429 } from "../types/PostV1Predictions.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { postV1Predictions } from "../client/postV1Predictions.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1PredictionsMutationKey = () => [{ url: '/v1/predictions' }] as const

export type PostV1PredictionsMutationKey = ReturnType<typeof postV1PredictionsMutationKey>

/**
 * @summary Submit a direction prediction for today's daily question
 * {@link /v1/predictions}
 */
export function usePostV1Predictions<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1PredictionsMutationResponse, ResponseErrorConfig<PostV1Predictions400 | PostV1Predictions422 | PostV1Predictions429>, {data: PostV1PredictionsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1PredictionsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1PredictionsMutationKey()

  return useMutation<PostV1PredictionsMutationResponse, ResponseErrorConfig<PostV1Predictions400 | PostV1Predictions422 | PostV1Predictions429>, {data: PostV1PredictionsMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1Predictions(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}