/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../http-client.ts";
import type { RequestConfig, ResponseErrorConfig } from "../../http-client.ts";
import type { PatchV1MeMutationRequest, PatchV1MeMutationResponse, PatchV1Me400, PatchV1Me404, PatchV1Me409 } from "../types/PatchV1Me.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { patchV1Me } from "../client/patchV1Me.ts";
import { useMutation } from "@tanstack/react-query";

export const patchV1MeMutationKey = () => [{ url: '/v1/me' }] as const

export type PatchV1MeMutationKey = ReturnType<typeof patchV1MeMutationKey>

/**
 * @summary Update current user's handle and/or avatar
 * {@link /v1/me}
 */
export function usePatchV1Me<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchV1MeMutationResponse, ResponseErrorConfig<PatchV1Me400 | PatchV1Me404 | PatchV1Me409>, {data?: PatchV1MeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PatchV1MeMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? patchV1MeMutationKey()

  return useMutation<PatchV1MeMutationResponse, ResponseErrorConfig<PatchV1Me400 | PatchV1Me404 | PatchV1Me409>, {data?: PatchV1MeMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return patchV1Me(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}