/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const assetsPastelEnum = {
    "peach": "peach",
    "mint": "mint",
    "sky": "sky",
    "lilac": "lilac"
} as const;

export type AssetsPastelEnum = (typeof assetsPastelEnum)[keyof typeof assetsPastelEnum];

/**
 * @description Default Response
*/
export type GetV1Assets200 = {
    /**
     * @type array
    */
    assets: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        pastel: AssetsPastelEnum;
        price_usd: (number | null);
        change_24h_pct: (number | null);
        cached_at: (number | null);
    }[];
};

export type GetV1AssetsQueryResponse = GetV1Assets200;

export type GetV1AssetsQuery = {
    Response: GetV1Assets200;
    Errors: any;
};