/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1TradesQueryParams = {
    /**
     * @minLength 1
     * @maxLength 200
     * @default 50
     * @type integer | undefined
    */
    limit?: number;
};

export const tradesSideEnum = {
    "buy": "buy",
    "sell": "sell"
} as const;

export type TradesSideEnum = (typeof tradesSideEnum)[keyof typeof tradesSideEnum];

/**
 * @description Default Response
*/
export type GetV1Trades200 = {
    /**
     * @type array
    */
    trades: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        asset_id: string;
        /**
         * @type string
        */
        side: TradesSideEnum;
        /**
         * @type string
        */
        usd_amount: string;
        /**
         * @type string
        */
        qty: string;
        /**
         * @type string
        */
        price_at_execution: string;
        /**
         * @type string
        */
        idempotency_key: string;
        /**
         * @type string
        */
        created_at: string;
    }[];
};

export type GetV1TradesQueryResponse = GetV1Trades200;

export type GetV1TradesQuery = {
    Response: GetV1Trades200;
    QueryParams: GetV1TradesQueryParams;
    Errors: any;
};