/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type GetV1Me200 = {
    /**
     * @type object
    */
    user: {
        /**
         * @type string, uuid
        */
        id: string;
        handle: (string | null);
        avatar: (string | null);
    };
    /**
     * @type object
    */
    portfolio: {
        /**
         * @type string
        */
        cash_usd: string;
        /**
         * @type array
        */
        holdings: {
            /**
             * @type string
            */
            asset_id: string;
            /**
             * @type string
            */
            qty: string;
            /**
             * @type string
            */
            cost_basis: string;
            price_usd: (number | null);
            value_usd: (string | null);
        }[];
        /**
         * @type string
        */
        total_value_usd: string;
    };
};

export const getV1Me404ErrorEnum = {
    "user_not_found": "user_not_found"
} as const;

export type GetV1Me404ErrorEnum = (typeof getV1Me404ErrorEnum)[keyof typeof getV1Me404ErrorEnum];

/**
 * @description Default Response
*/
export type GetV1Me404 = {
    /**
     * @type string
    */
    error: GetV1Me404ErrorEnum;
};

export type GetV1MeQueryResponse = GetV1Me200;

export type GetV1MeQuery = {
    Response: GetV1Me200;
    Errors: GetV1Me404;
};