/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getV1Health200StatusEnum = {
    "ok": "ok"
} as const;

export type GetV1Health200StatusEnum = (typeof getV1Health200StatusEnum)[keyof typeof getV1Health200StatusEnum];

/**
 * @description Default Response
*/
export type GetV1Health200 = {
    /**
     * @type string
    */
    status: GetV1Health200StatusEnum;
};

export type GetV1HealthQueryResponse = GetV1Health200;

export type GetV1HealthQuery = {
    Response: GetV1Health200;
    Errors: any;
};