/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1HandlesCheckQueryParams = {
    /**
     * @minLength 1
     * @maxLength 40
     * @type string
    */
    handle: string;
};

export const getV1HandlesCheck200ReasonEnum = {
    "invalid_format": "invalid_format",
    "reserved": "reserved",
    "taken": "taken"
} as const;

export type GetV1HandlesCheck200ReasonEnum = (typeof getV1HandlesCheck200ReasonEnum)[keyof typeof getV1HandlesCheck200ReasonEnum];

/**
 * @description Default Response
*/
export type GetV1HandlesCheck200 = {
    /**
     * @type boolean
    */
    available: boolean;
    reason: (GetV1HandlesCheck200ReasonEnum | null);
};

export type GetV1HandlesCheckQueryResponse = GetV1HandlesCheck200;

export type GetV1HandlesCheckQuery = {
    Response: GetV1HandlesCheck200;
    QueryParams: GetV1HandlesCheckQueryParams;
    Errors: any;
};