/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const questionDirectionResolvedEnum = {
    "up": "up",
    "down": "down",
    "tie": "tie"
} as const;

export type QuestionDirectionResolvedEnum = (typeof questionDirectionResolvedEnum)[keyof typeof questionDirectionResolvedEnum];

export const myPredictionDirectionEnum = {
    "up": "up",
    "down": "down"
} as const;

export type MyPredictionDirectionEnum = (typeof myPredictionDirectionEnum)[keyof typeof myPredictionDirectionEnum];

export const myPredictionStatusEnum = {
    "pending": "pending",
    "correct": "correct",
    "wrong": "wrong",
    "tie": "tie"
} as const;

export type MyPredictionStatusEnum = (typeof myPredictionStatusEnum)[keyof typeof myPredictionStatusEnum];

/**
 * @description Default Response
*/
export type GetV1DailyQuestion200 = {
    question: ({
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        date: string;
        /**
         * @type string
        */
        asset_id: string;
        direction_resolved: (QuestionDirectionResolvedEnum | null);
        resolved_at: (string | null);
        /**
         * @type string
        */
        created_at: string;
    } | null);
    my_prediction: ({
        /**
         * @type string
        */
        direction: MyPredictionDirectionEnum;
        /**
         * @type number
        */
        stake: number;
        /**
         * @type string
        */
        status: MyPredictionStatusEnum;
        payout: (number | null);
    } | null);
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
    */
    points_balance: number;
};

export type GetV1DailyQuestionQueryResponse = GetV1DailyQuestion200;

export type GetV1DailyQuestionQuery = {
    Response: GetV1DailyQuestion200;
    Errors: any;
};