/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type GetV1LearnState200 = {
    /**
     * @type array
    */
    tracks: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type number
        */
        lessons_total: number;
        /**
         * @type number
        */
        lessons_completed: number;
    }[];
    /**
     * @type array
    */
    lessons: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        track_id: string;
        completed_at: (string | null);
        quiz_score: (number | null);
    }[];
};

export type GetV1LearnStateQueryResponse = GetV1LearnState200;

export type GetV1LearnStateQuery = {
    Response: GetV1LearnState200;
    Errors: any;
};