/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type GetV1PushVapidKey200 = {
    /**
     * @type string
    */
    vapid_public_key: string;
};

export type GetV1PushVapidKeyQueryResponse = GetV1PushVapidKey200;

export type GetV1PushVapidKeyQuery = {
    Response: GetV1PushVapidKey200;
    Errors: any;
};