/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1LeaderboardQueryParams = {
    /**
     * @minLength 1
     * @maxLength 200
     * @default 50
     * @type integer | undefined
    */
    limit?: number;
};

/**
 * @description Default Response
*/
export type GetV1Leaderboard200 = {
    /**
     * @type string
    */
    week_starting_date: string;
    /**
     * @type array
    */
    entries: {
        /**
         * @minLength -9007199254740991
         * @maxLength 9007199254740991
         * @type integer
        */
        rank: number;
        /**
         * @type string, uuid
        */
        user_id: string;
        handle: (string | null);
        /**
         * @minLength -9007199254740991
         * @maxLength 9007199254740991
         * @type integer
        */
        composite_score: number;
    }[];
    my_entry: ({
        /**
         * @minLength -9007199254740991
         * @maxLength 9007199254740991
         * @type integer
        */
        rank: number;
        /**
         * @type string, uuid
        */
        user_id: string;
        handle: (string | null);
        /**
         * @minLength -9007199254740991
         * @maxLength 9007199254740991
         * @type integer
        */
        composite_score: number;
    } | null);
};

export type GetV1LeaderboardQueryResponse = GetV1Leaderboard200;

export type GetV1LeaderboardQuery = {
    Response: GetV1Leaderboard200;
    QueryParams: GetV1LeaderboardQueryParams;
    Errors: any;
};