/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type PatchV1Me200 = {
    /**
     * @type object
    */
    user: {
        /**
         * @type string, uuid
        */
        id: string;
        handle: (string | null);
        avatar: (string | null);
    };
};

export const patchV1Me400ErrorEnum = {
    "invalid_handle_format": "invalid_handle_format",
    "handle_reserved": "handle_reserved",
    "handle_taken": "handle_taken"
} as const;

export type PatchV1Me400ErrorEnum = (typeof patchV1Me400ErrorEnum)[keyof typeof patchV1Me400ErrorEnum];

/**
 * @description Default Response
*/
export type PatchV1Me400 = {
    /**
     * @type string
    */
    error: PatchV1Me400ErrorEnum;
};

export const patchV1Me404ErrorEnum = {
    "user_not_found": "user_not_found"
} as const;

export type PatchV1Me404ErrorEnum = (typeof patchV1Me404ErrorEnum)[keyof typeof patchV1Me404ErrorEnum];

/**
 * @description Default Response
*/
export type PatchV1Me404 = {
    /**
     * @type string
    */
    error: PatchV1Me404ErrorEnum;
};

export const patchV1Me409ErrorEnum = {
    "invalid_handle_format": "invalid_handle_format",
    "handle_reserved": "handle_reserved",
    "handle_taken": "handle_taken"
} as const;

export type PatchV1Me409ErrorEnum = (typeof patchV1Me409ErrorEnum)[keyof typeof patchV1Me409ErrorEnum];

/**
 * @description Default Response
*/
export type PatchV1Me409 = {
    /**
     * @type string
    */
    error: PatchV1Me409ErrorEnum;
};

export const patchV1MeMutationRequestAvatarEnum = {
    "peach": "peach",
    "mint": "mint",
    "sky": "sky",
    "lilac": "lilac"
} as const;

export type PatchV1MeMutationRequestAvatarEnum = (typeof patchV1MeMutationRequestAvatarEnum)[keyof typeof patchV1MeMutationRequestAvatarEnum];

export type PatchV1MeMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 40
     * @type string | undefined
    */
    handle?: string;
    /**
     * @type string | undefined
    */
    avatar?: PatchV1MeMutationRequestAvatarEnum;
};

export type PatchV1MeMutationResponse = PatchV1Me200;

export type PatchV1MeMutation = {
    Response: PatchV1Me200;
    Request: PatchV1MeMutationRequest;
    Errors: PatchV1Me400 | PatchV1Me404 | PatchV1Me409;
};