/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1LessonsIdCompletePathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const postV1LessonsIdComplete200TrackJustCompletedEnum = {
    "fundamentals": "fundamentals",
    "markets": "markets",
    "safety": "safety"
} as const;

export type PostV1LessonsIdComplete200TrackJustCompletedEnum = (typeof postV1LessonsIdComplete200TrackJustCompletedEnum)[keyof typeof postV1LessonsIdComplete200TrackJustCompletedEnum];

/**
 * @description Default Response
*/
export type PostV1LessonsIdComplete200 = {
    /**
     * @type object
    */
    progress: {
        /**
         * @type string
        */
        lesson_id: string;
        /**
         * @type number
        */
        quiz_score: number;
        /**
         * @type string
        */
        completed_at: string;
        /**
         * @type string
        */
        updated_at: string;
    };
    /**
     * @type boolean
    */
    is_first_lesson: boolean;
    track_just_completed: (PostV1LessonsIdComplete200TrackJustCompletedEnum | null);
};

export const postV1LessonsIdComplete201TrackJustCompletedEnum = {
    "fundamentals": "fundamentals",
    "markets": "markets",
    "safety": "safety"
} as const;

export type PostV1LessonsIdComplete201TrackJustCompletedEnum = (typeof postV1LessonsIdComplete201TrackJustCompletedEnum)[keyof typeof postV1LessonsIdComplete201TrackJustCompletedEnum];

/**
 * @description Default Response
*/
export type PostV1LessonsIdComplete201 = {
    /**
     * @type object
    */
    progress: {
        /**
         * @type string
        */
        lesson_id: string;
        /**
         * @type number
        */
        quiz_score: number;
        /**
         * @type string
        */
        completed_at: string;
        /**
         * @type string
        */
        updated_at: string;
    };
    /**
     * @type boolean
    */
    is_first_lesson: boolean;
    track_just_completed: (PostV1LessonsIdComplete201TrackJustCompletedEnum | null);
};

/**
 * @description Default Response
*/
export type PostV1LessonsIdComplete400 = any;

export const postV1LessonsIdComplete404ErrorEnum = {
    "lesson_not_found": "lesson_not_found",
    "invalid_score": "invalid_score"
} as const;

export type PostV1LessonsIdComplete404ErrorEnum = (typeof postV1LessonsIdComplete404ErrorEnum)[keyof typeof postV1LessonsIdComplete404ErrorEnum];

/**
 * @description Default Response
*/
export type PostV1LessonsIdComplete404 = {
    /**
     * @type string
    */
    error: PostV1LessonsIdComplete404ErrorEnum;
};

export type PostV1LessonsIdCompleteMutationRequest = {
    /**
     * @minLength 0
     * @maxLength 100
     * @type integer
    */
    quiz_score: number;
};

export type PostV1LessonsIdCompleteMutationResponse = (PostV1LessonsIdComplete200 | PostV1LessonsIdComplete201);

export type PostV1LessonsIdCompleteMutation = {
    Response: PostV1LessonsIdComplete200 | PostV1LessonsIdComplete201;
    Request: PostV1LessonsIdCompleteMutationRequest;
    PathParams: PostV1LessonsIdCompletePathParams;
    Errors: PostV1LessonsIdComplete400 | PostV1LessonsIdComplete404;
};