/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const tradeSideEnum = {
    "buy": "buy",
    "sell": "sell"
} as const;

export type TradeSideEnum = (typeof tradeSideEnum)[keyof typeof tradeSideEnum];

/**
 * @description Default Response
*/
export type PostV1Trades200 = {
    /**
     * @type object
    */
    trade: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        asset_id: string;
        /**
         * @type string
        */
        side: TradeSideEnum;
        /**
         * @type string
        */
        usd_amount: string;
        /**
         * @type string
        */
        qty: string;
        /**
         * @type string
        */
        price_at_execution: string;
        /**
         * @type string
        */
        idempotency_key: string;
        /**
         * @type string
        */
        created_at: string;
    };
    /**
     * @type boolean
    */
    is_first_trade: boolean;
};

export const tradeSideEnum2 = {
    "buy": "buy",
    "sell": "sell"
} as const;

export type TradeSideEnum2 = (typeof tradeSideEnum2)[keyof typeof tradeSideEnum2];

/**
 * @description Default Response
*/
export type PostV1Trades201 = {
    /**
     * @type object
    */
    trade: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        asset_id: string;
        /**
         * @type string
        */
        side: TradeSideEnum2;
        /**
         * @type string
        */
        usd_amount: string;
        /**
         * @type string
        */
        qty: string;
        /**
         * @type string
        */
        price_at_execution: string;
        /**
         * @type string
        */
        idempotency_key: string;
        /**
         * @type string
        */
        created_at: string;
    };
    /**
     * @type boolean
    */
    is_first_trade: boolean;
};

/**
 * @description Default Response
*/
export type PostV1Trades400 = any;

export const postV1Trades422ErrorEnum = {
    "insufficient_cash": "insufficient_cash",
    "insufficient_qty": "insufficient_qty",
    "unknown_asset": "unknown_asset",
    "invalid_amount": "invalid_amount"
} as const;

export type PostV1Trades422ErrorEnum = (typeof postV1Trades422ErrorEnum)[keyof typeof postV1Trades422ErrorEnum];

/**
 * @description Default Response
*/
export type PostV1Trades422 = {
    /**
     * @type string
    */
    error: PostV1Trades422ErrorEnum;
};

/**
 * @description Default Response
*/
export type PostV1Trades429 = any;

export const postV1Trades503ErrorEnum = {
    "price_unavailable": "price_unavailable"
} as const;

export type PostV1Trades503ErrorEnum = (typeof postV1Trades503ErrorEnum)[keyof typeof postV1Trades503ErrorEnum];

/**
 * @description Default Response
*/
export type PostV1Trades503 = {
    /**
     * @type string
    */
    error: PostV1Trades503ErrorEnum;
};

export const postV1TradesMutationRequestAssetIdEnum = {
    "BTC": "BTC",
    "ETH": "ETH",
    "SOL": "SOL",
    "USDC": "USDC",
    "BNB": "BNB",
    "XRP": "XRP",
    "ADA": "ADA",
    "DOGE": "DOGE",
    "AVAX": "AVAX",
    "LINK": "LINK",
    "DOT": "DOT",
    "TON": "TON"
} as const;

export type PostV1TradesMutationRequestAssetIdEnum = (typeof postV1TradesMutationRequestAssetIdEnum)[keyof typeof postV1TradesMutationRequestAssetIdEnum];

export const postV1TradesMutationRequestSideEnum = {
    "buy": "buy",
    "sell": "sell"
} as const;

export type PostV1TradesMutationRequestSideEnum = (typeof postV1TradesMutationRequestSideEnum)[keyof typeof postV1TradesMutationRequestSideEnum];

export type PostV1TradesMutationRequest = {
    /**
     * @type string
    */
    asset_id: PostV1TradesMutationRequestAssetIdEnum;
    /**
     * @type string
    */
    side: PostV1TradesMutationRequestSideEnum;
    /**
     * @pattern ^\d+(\.\d{1,8})?$
     * @type string
    */
    usd_amount: string;
    /**
     * @minLength 1
     * @maxLength 120
     * @type string
    */
    idempotency_key: string;
};

export type PostV1TradesMutationResponse = (PostV1Trades200 | PostV1Trades201);

export type PostV1TradesMutation = {
    Response: PostV1Trades200 | PostV1Trades201;
    Request: PostV1TradesMutationRequest;
    Errors: PostV1Trades400 | PostV1Trades422 | PostV1Trades429 | PostV1Trades503;
};