/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type PostV1AuthRefresh200 = {
    /**
     * @type string
    */
    access_token: string;
    /**
     * @type string
    */
    refresh_token: string;
};

export const postV1AuthRefresh401ErrorEnum = {
    "invalid_refresh_token": "invalid_refresh_token"
} as const;

export type PostV1AuthRefresh401ErrorEnum = (typeof postV1AuthRefresh401ErrorEnum)[keyof typeof postV1AuthRefresh401ErrorEnum];

/**
 * @description Default Response
*/
export type PostV1AuthRefresh401 = {
    /**
     * @type string
    */
    error: PostV1AuthRefresh401ErrorEnum;
};

export type PostV1AuthRefreshMutationRequest = {
    /**
     * @minLength 20
     * @type string
    */
    refresh_token: string;
};

export type PostV1AuthRefreshMutationResponse = PostV1AuthRefresh200;

export type PostV1AuthRefreshMutation = {
    Response: PostV1AuthRefresh200;
    Request: PostV1AuthRefreshMutationRequest;
    Errors: PostV1AuthRefresh401;
};