/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type PostV1PushUnsubscribe204 = any;

export type PostV1PushUnsubscribeMutationRequest = {
    /**
     * @type string, uri
    */
    endpoint: string;
};

export type PostV1PushUnsubscribeMutationResponse = PostV1PushUnsubscribe204;

export type PostV1PushUnsubscribeMutation = {
    Response: PostV1PushUnsubscribe204;
    Request: PostV1PushUnsubscribeMutationRequest;
    Errors: any;
};