/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type PostV1Predictions200 = {
    /**
     * @type object
    */
    prediction: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        direction: string;
        /**
         * @type number
        */
        stake: number;
        /**
         * @type string
        */
        status: string;
        payout: (number | null);
        /**
         * @type string
        */
        created_at: string;
    };
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
    */
    points_balance: number;
};

/**
 * @description Default Response
*/
export type PostV1Predictions201 = {
    /**
     * @type object
    */
    prediction: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        direction: string;
        /**
         * @type number
        */
        stake: number;
        /**
         * @type string
        */
        status: string;
        payout: (number | null);
        /**
         * @type string
        */
        created_at: string;
    };
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
    */
    points_balance: number;
};

/**
 * @description Default Response
*/
export type PostV1Predictions400 = any;

export const postV1Predictions422ErrorEnum = {
    "question_not_found": "question_not_found",
    "question_resolved": "question_resolved",
    "invalid_direction": "invalid_direction",
    "invalid_stake": "invalid_stake",
    "insufficient_points": "insufficient_points"
} as const;

export type PostV1Predictions422ErrorEnum = (typeof postV1Predictions422ErrorEnum)[keyof typeof postV1Predictions422ErrorEnum];

/**
 * @description Default Response
*/
export type PostV1Predictions422 = {
    /**
     * @type string
    */
    error: PostV1Predictions422ErrorEnum;
};

/**
 * @description Default Response
*/
export type PostV1Predictions429 = any;

export const postV1PredictionsMutationRequestDirectionEnum = {
    "up": "up",
    "down": "down"
} as const;

export type PostV1PredictionsMutationRequestDirectionEnum = (typeof postV1PredictionsMutationRequestDirectionEnum)[keyof typeof postV1PredictionsMutationRequestDirectionEnum];

export type PostV1PredictionsMutationRequest = {
    /**
     * @type string, uuid
    */
    daily_question_id: string;
    /**
     * @type string
    */
    direction: PostV1PredictionsMutationRequestDirectionEnum;
    /**
     * @minLength 100
     * @maxLength 500
     * @type integer
    */
    stake: number;
    /**
     * @minLength 1
     * @maxLength 120
     * @type string
    */
    idempotency_key: string;
};

export type PostV1PredictionsMutationResponse = (PostV1Predictions200 | PostV1Predictions201);

export type PostV1PredictionsMutation = {
    Response: PostV1Predictions200 | PostV1Predictions201;
    Request: PostV1PredictionsMutationRequest;
    Errors: PostV1Predictions400 | PostV1Predictions422 | PostV1Predictions429;
};