/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type PostV1PushSubscribe204 = any;

export type PostV1PushSubscribeMutationRequest = {
    /**
     * @type string, uri
    */
    endpoint: string;
    /**
     * @minLength 1
     * @type string
    */
    p256dh: string;
    /**
     * @minLength 1
     * @type string
    */
    auth: string;
};

export type PostV1PushSubscribeMutationResponse = PostV1PushSubscribe204;

export type PostV1PushSubscribeMutation = {
    Response: PostV1PushSubscribe204;
    Request: PostV1PushSubscribeMutationRequest;
    Errors: any;
};