/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Default Response
*/
export type PostV1AuthDevice200 = {
    /**
     * @type string
    */
    access_token: string;
    /**
     * @type string
    */
    refresh_token: string;
    /**
     * @type object
    */
    user: {
        /**
         * @type string, uuid
        */
        id: string;
        handle: (string | null);
    };
};

export type PostV1AuthDeviceMutationRequest = {
    /**
     * @type string, uuid
    */
    device_uuid: string;
};

export type PostV1AuthDeviceMutationResponse = PostV1AuthDevice200;

export type PostV1AuthDeviceMutation = {
    Response: PostV1AuthDevice200;
    Request: PostV1AuthDeviceMutationRequest;
    Errors: any;
};